language: node_js
node_js:
  - "node"
notifications:
  email:
    on_success: never
    on_failure: always
sudo: required
services:
  - docker
script:
  - npm ci
  - docker build -t tdekarz/omega:latest .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
